### ISSUE TITLE
Can't install using pip install -e .

### ISSUE THREAD

**Issue by meetmangukiya** [timofurrer/ramlient#3]
```
± % pip install -e .                                                                                                                                  !10086
Obtaining file:///sub/ghubby/meet/ramlient
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/sub/ghubby/meet/ramlient/setup.py", line 50, in <module>
        install_requires=list(x.name for x in parse_requirements("requirements.txt")),
      File "/sub/ghubby/meet/ramlient/setup.py", line 50, in <genexpr>
        install_requires=list(x.name for x in parse_requirements("requirements.txt")),
      File "/sub/ghubby/meet/ramlient/.env/lib/python3.5/site-packages/pip/req/req_file.py", line 79, in parse_requirements
        "parse_requirements() missing 1 required keyword argument: "
    TypeError: parse_requirements() missing 1 required keyword argument: 'session'
```

**Comment by timofurrer** [comment]
We shouldn't depend on `pip.req` in `setup.py`. It's anyway not how the `requirements.txt` should be used.

See https://github.com/timofurrer/colorful/blob/master/setup.py for a sane way to implement the `setup.py`.
